package org.example.greeting.server;

import com.proto.greeting.GreetingRequest;
import com.proto.greeting.GreetingResponse;
import com.proto.greeting.GreetingServiceGrpc;
import io.grpc.stub.StreamObserver;

// generateProto task created GreetingServiceGrpc.GreetingServiceImplBase abstract class
public class GreetingServerImpl extends GreetingServiceGrpc.GreetingServiceImplBase {

    // Override the greet method in base class that was auto-generated by the protobuf (greet.proto)
    @Override
    public void greet(GreetingRequest request, StreamObserver<GreetingResponse> responseObserver){
        responseObserver.onNext(GreetingResponse.newBuilder().setResult("Hello " + request.getFirstName()).build());
        responseObserver.onCompleted();
    }

}
